CREATE TABLE tb_task (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(100) NOT NULL,

    description TEXT,

    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDENT', 'IN_PROGRESS', 'COMPLETED', 'CANCELED')),

    priority INTEGER,

    due_date DATE
);