CREATE TABLE tb_user (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Chave primária numérica
                         username VARCHAR(100) NOT NULL UNIQUE,
                         password VARCHAR(255) NOT NULL
);