CREATE TABLE tb_attachment (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               file_name VARCHAR(255) NOT NULL,
                               file_type VARCHAR(100),
                               size BIGINT NOT NULL,
                               file_path VARCHAR(500) NOT NULL,
                               task_id BIGINT NOT NULL,
                               CONSTRAINT fk_attachment_task FOREIGN KEY (task_id) REFERENCES tb_task(id)
);